### ISSUE TITLE
Scroll wheel for larger grid sizes perhaps?

### ISSUE THREAD

**Issue by Nathan22211** [TeamAOF/Artis#6]
considering I've seen other mods do this: why couldn't you use a scroll wheel for larger sized grids

**Comment by Shrimpstress** [comment]
I'm not sure if anything bigger than 9x9 would be feasible even if it could fit on a screen.

**Comment by Shrimpstress** [comment]
Plus, this mods main focus is **not** to have larger and larger grids, but rather the ability to require tools in order to craft certain things. There are no plans to ever support anything higher than 9x9, and we're only supporting 9x9 because it is a standard that current mods have adopted. Anything higher would be so tedious (especially with the addition of having to scroll) that it would not be worth the effort of implementing this functionality.

**Comment by LemmaEOF** [comment]
Also, scrolling item slots is difficult at best. I don't wanna have to deal with the maintenance of that.
